stages:
  - hash

generate_and_push_md5:
  stage: hash
  image: alpine:latest
  before_script:
    - apk add --no-cache git bash coreutils
  script:
    - 'md5sum sample_bed.txt > sample_bed.txt.md5'
    - 'git config --global user.name "CI Bot"'
    - 'git config --global user.email "ci@example.com"'
    - 'git checkout "$CI_COMMIT_BRANCH"'
    - 'git add sample_bed.txt.md5'
    - 'git commit -m "CI: actualiza hash MD5 de sample_bed.txt" || echo "Nada que commitear"'
    - 'git push https://gitlab-ci-token:${CI_PUSH_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git HEAD:$CI_COMMIT_BRANCH'
