name: Generate and Push MD5

on:
  push:
    branches:
      - master
    paths:
      - sample_bed.txt
      - sample_bed.txt.md5

jobs:
  generate_and_push_md5:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate MD5 hash
        run: md5sum sample_bed.txt > sample_bed.txt.md5

      - name: Commit and push MD5 file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "CI Bot"
          git config user.email "ci@example.com"
          git add sample_bed.txt.md5
          git commit -m "CI: actualiza hash MD5 de sample_bed.txt" || echo "Nada que commitear"
          git push
